# Site settings
title: ClearCove Software Inc.
email: jhund@clearcove.ca
description: We Build Information Power Tools
baseurl: ''
url: http://clearcove.ca
twitter_username: jhund
github_username:  jhund

# Build settings
markdown: kramdown
